### PR TITLE
Auto-generated data_bridges_client, with WFP token refresh workflow

### PR DESCRIPTION
**Pull request by paololucchino**
This PR:
- Adds an auto-generated DataBridges API client based on the swagger.json in catalog.api.wfp.org
- Refactors existing custom WFP functionality to refresh authentication tokens based on key and secret in a way that can be used with the auto-generated client. See example in [README.md](README.md)
- Adds the `generate` folder with documentation and scripts to update the client when new endpoints are added to the swagger.json.

Issues:
- The auto-generated package uses `urllib3` for requests while we use `httpx` to refresh the token. The latter dependency should be redundant as the token request should be equally possible with `urllib3`. Somehow however I was not able to get it to work. See implementation [here](https://github.com/WFP-VAM/DataBridgesAPI/blob/a327b06cca1dd250bbcd8371faa33d18fd45c8de/data_bridges_client/token.py#L41) which does not work. Something very simple is escaping me! Help welcome! In any case, it is a non-blocking issue; it just means we have an additional dependency.

Warnings:
- We should handle the merge into `main` carefully if we have downstream consumers of the client currently in that branch. Downstream consumers will need to pin their installation to a specific version / tag / commit.

### CODE REVIEW

**Comment by pierrz** [comment]
Hi Paolo, I'm taking the review over from Giulia. I installed the package and could run with the provided "getting started" section and I'm getting a JSON response, so it seems to work (as expected ...? Cannot be sure 100% as I'm very new in RAM). 

Some issues / thoughts:
- Had to install `urllib3` and `python-dateutil` to run the example code, I think it is related to what you also explain above. I can check further to have that also installed with additional pip commands. Or as you proposed this can just be clearly documented as dependencies.
- Regarding the merge in main which could impact other users, maybe we can simply create a `development` branch and use this as an intermediary point, test things out and get some feedback from other users, and in time merge it `development` into `main`

Otherwise it seems good to me but of course I couldn't check the 230 changed files :)

**Comment by martinig94** [comment]
Hi @paololucchino ,
Thank you very much for your work and apologies for getting back to you only now.
I have run few tests and things seem to work for me besides the following issue. I actually hope that I am doing something silly, please let me know what you think.

In this case for me the API response is not a json file, not clear why. I can get a string with `api_response.read()` but then loading it as json becomes a bit annoying.

        KEY = ""
        SECRET = ""
        token = WfpApiToken(api_key=KEY, api_secret=SECRET)
        # Enter a context with an instance of the API client using a fresh token
        with data_bridges_client.ApiClient(token.refresh_configuration()) as api_client:
            # Create an instance of the API class
            api_instance = economic_data_api.EconomicDataApi(api_client)
            country_code = "COL"  # str | The code to identify the country. It can be a ISO-3166 Alpha 3 code or the VAM internal admin0code (optional)
            format = "json"  # str | Output format: [JSON|CSV] Json is the default value (optional) (default to "json")
            env = "prod"  # str | Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org (optional)
            try:
                # Provides the list of categories.
                api_response = api_instance.economic_data_indicator_name_get(
                      indicator_name="Food Inflation",
                      iso3=iso3,
                      start_date=datetime.datetime(2023,1,1),
                      format=format,
                      env=env,
                )
            except data_bridges_client.ApiException as e:
                print(
                    "Exception when calling EconomicDataApi->economic_data_indicator_name_get: %s\n"
                    % e
                )


@pierrz  not sure if you tested the above, in case your help is very appreciated.
Regarding the packages to be installed, they are listed in the requirements.txt so when pip installed the packages they were automatically installed. What was the issue you were experiencing?

**Comment by martinig94** [comment]
@paololucchino Are you also planning to create a similar module for the HDC API? (: it would be amazing!

**Comment by paololucchino** [comment]
Hi @martinig94,

Indeed a strange API response. It seems to be of type `<class '_io.BufferedReader'>`, which is consistent with the autogenerated [documentation](https://github.com/WFP-VAM/DataBridgesAPI/blob/use-open-api-generator/docs/EconomicDataApi.md#return-type-1) which states that indeed the API returns a file. Is this the intended behaviour @ValerioGiuffrida?

That said, converting to dictionary can be achieved (annoyingly but) easily:
```
import json
r = json.loads(api_response.read())
```

Re: dependencies (cc @pierrz ), I had added these in the [setup.py](https://github.com/WFP-VAM/DataBridgesAPI/blob/use-open-api-generator/setup.py#L23), and (if recall correctly) these were pulled in when calling `pip install .`. Perhaps someone else can check?

Agreed, let's have this feature branch merge into a `dev` branch first. I have created that and update this PR.

@martinig94 in general, I think we should have a single cross-RAM client for each API. We have been working on a package to interact with the HDC STAC API (for raw rasters) but not the HDC STAC (yet?). If you / someone wanted to try autogenerating one, this should just involve following the instructions [here](https://github.com/WFP-VAM/DataBridgesAPI/blob/use-open-api-generator/generate/README.md) using the swagger.json for the HDC STAT API (I imagine available in our API Catalogue) into a new repository.

**Comment by ValerioGiuffrida** [comment]
In some cases yes, but not in the one indicated by the API call Giulia shared. 
In particular, the format parameter can be switched to CSV to export directly a file. 

OFF TOPIC: This is useful for the direct download of data, but indeed the DataBridges and DataViz architecture are encountering limitations due to this direct use of database resources and APIs to share data in bulk. We will likely have to work on this in the future!

**Comment by martinig94** [comment]
Hi @paololucchino, @ValerioGiuffrida 

thanks for the reply. I agree that the documentation on the output is correct, but I still find this part a bit confusing. What do you think? I guess this is more an issue of the API itself than this code.
image

**Comment by ValerioGiuffrida** [comment]
@paololucchino I tested the response to the query https://api.wfp.org/vam-data-bridges/1.3.1/EconomicData/foodinflation?page=1&iso3=AFG&format=JSON and it appears to be a JSON format to me...

Maybe it's an issue on how the open-api-generator interprets the format parameter?

**Comment by paololucchino** [comment]
While technically without official Approval, the conversation suggests I can merge this into `dev`, so I will do so now.

**Pull request merged**
